"""Knowledge Profile ("skill.md") — evidence-based, never manually set.

Mastery/trend are always derived from review_state + review_history.
Visibility is enforced at generation time: a 'shared'-audience export never
touches private entries (tech doc §2.7).
"""
from datetime import timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session as DBSession

from app.db.base import utcnow
from app.models import KnowledgeProfileEntry, KnowledgeUnit, ReviewHistory, ReviewState, User

PERFORMANCE_SCORE = {"correct": 2, "partial": 1, "incorrect": 0}
STALE_OVERDUE_FACTOR = 2.0  # overdue by 2x its interval -> stale


def _effective_mastery(state: ReviewState) -> str:
    now = utcnow()
    interval = max(float(state.interval_days), 1.0)
    overdue = now - state.next_review_at
    if state.mastery_status in ("learning", "consolidated") and overdue > timedelta(days=interval * STALE_OVERDUE_FACTOR):
        return "stale"
    return state.mastery_status


def _retention_trend(db: DBSession, user_id: str, unit_id: str) -> str | None:
    scores = [
        PERFORMANCE_SCORE[p]
        for (p,) in db.execute(
            select(ReviewHistory.performance)
            .where(ReviewHistory.user_id == user_id, ReviewHistory.unit_id == unit_id)
            .order_by(ReviewHistory.reviewed_at.desc())
            .limit(4)
        ).all()
    ]
    if len(scores) < 2:
        return None
    recent, earlier = scores[0], scores[-1]  # newest vs oldest in window
    if recent > earlier:
        return "improving"
    if recent < earlier:
        return "declining"
    return "stable"


def compute_profile(db: DBSession, user: User) -> list[tuple[KnowledgeProfileEntry, KnowledgeUnit]]:
    """Recomputes profile entries from evidence and upserts them."""
    rows = db.execute(
        select(ReviewState, KnowledgeUnit)
        .join(KnowledgeUnit, KnowledgeUnit.id == ReviewState.unit_id)
        .where(ReviewState.user_id == user.id, KnowledgeUnit.deleted_at.is_(None))
    ).all()

    existing = {
        e.unit_id: e
        for e in db.scalars(
            select(KnowledgeProfileEntry).where(KnowledgeProfileEntry.user_id == user.id)
        ).all()
    }

    result = []
    for state, unit in rows:
        mastery = _effective_mastery(state)
        trend = _retention_trend(db, user.id, unit.id)
        entry = existing.get(unit.id)
        if entry is None:
            entry = KnowledgeProfileEntry(
                user_id=user.id, unit_id=unit.id, mastery_status=mastery, retention_trend=trend
            )
            db.add(entry)
            db.flush()
        else:
            entry.mastery_status = mastery
            entry.retention_trend = trend
            entry.last_computed_at = utcnow()
        result.append((entry, unit))
    db.commit()
    return result


def export_markdown(db: DBSession, user: User, audience: str = "private") -> str:
    """audience='shared' includes ONLY shared entries — enforced here, at generation."""
    entries = compute_profile(db, user)
    if audience == "shared":
        entries = [(e, u) for e, u in entries if e.visibility == "shared"]

    by_status: dict[str, list] = {"consolidated": [], "learning": [], "new": [], "stale": []}
    for entry, unit in entries:
        by_status.setdefault(entry.mastery_status, []).append((entry, unit))

    name = user.display_name or user.email.split("@")[0]
    lines = [
        f"# Knowledge Profile — {name}",
        "",
        f"_Generated by Trivium on {utcnow().strftime('%Y-%m-%d %H:%M UTC')}. "
        "Every entry below is evidence-based: derived from demonstrated recall performance, never self-reported._",
        "",
    ]
    section_titles = {
        "consolidated": "## Mastered (consolidated)",
        "learning": "## In progress",
        "new": "## Recently captured (not yet reviewed)",
        "stale": "## Needs refreshing (stale)",
    }
    trend_labels = {"improving": "trend: improving", "stable": "trend: stable", "declining": "trend: declining"}
    for status in ("consolidated", "learning", "stale", "new"):
        group = by_status.get(status, [])
        if not group:
            continue
        lines.append(section_titles[status])
        lines.append("")
        for entry, unit in sorted(group, key=lambda p: p[1].title.lower()):
            meta = [unit.unit_type, unit.difficulty or "intermediate", f"fidelity: {unit.source_fidelity}"]
            if entry.retention_trend:
                meta.append(trend_labels[entry.retention_trend])
            lines.append(f"- **{unit.title}** ({', '.join(meta)})")
            if unit.summary:
                lines.append(f"  - {unit.summary[:200]}")
        lines.append("")
    if len(entries) == 0:
        lines.append("_No evidence recorded yet — complete reviews to build your profile._")
    return "\n".join(lines)
