# initial schema
#
# Revision ID: 528e4ffa07ac
# Revises: 
# Create Date: 2026-07-26 15:49:23.508927

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


revision: str = '528e4ffa07ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('learning_intensity', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('learning_artifacts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_ref', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('generated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('triggered_by', sa.String(length=30), nullable=False),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_user', 'learning_artifacts', ['user_id', 'generated_at'], unique=False)
    op.create_table('metrics_events',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_events_user', 'metrics_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_user', 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('project_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('source_tool', sa.String(length=50), nullable=False),
    sa.Column('source_fidelity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('raw_log_ref', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user_project', 'sessions', ['user_id', 'project_id'], unique=False)
    op.create_table('knowledge_units',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('project_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('source_fidelity', sa.String(length=20), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('embedding_ref', sa.Text(), nullable=True),
    sa.Column('extracted_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_units_project', 'knowledge_units', ['project_id'], unique=False)
    op.create_index('idx_knowledge_units_user_time', 'knowledge_units', ['user_id', 'extracted_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('authored_by', sa.String(length=10), nullable=True),
    sa.Column('code_diff', sa.Text(), nullable=True),
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'messages', ['session_id', 'timestamp'], unique=False)
    op.create_table('format_decisions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('detected_type', sa.String(length=30), nullable=False),
    sa.Column('chosen_format', sa.String(length=30), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('signal', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('independence_metrics',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('window_start', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('window_end', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('computed_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_profile_entries',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('mastery_status', sa.String(length=20), nullable=False),
    sa.Column('retention_trend', sa.String(length=20), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('last_computed_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_entries_user', 'knowledge_profile_entries', ['user_id'], unique=False)
    op.create_table('knowledge_unit_relations',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('related_unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_unit_id'], ['knowledge_units.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ku_relations_unit', 'knowledge_unit_relations', ['unit_id'], unique=False)
    op.create_table('learning_artifact_units',
    sa.Column('artifact_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['learning_artifacts.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.PrimaryKeyConstraint('artifact_id', 'unit_id')
    )
    op.create_table('review_history',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('artifact_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('performance', sa.String(length=20), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['learning_artifacts.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_history_unit_offset', 'review_history', ['unit_id', 'day_offset'], unique=False)
    op.create_table('review_state',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('unit_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('next_review_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('interval_days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('first_review_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('mastery_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unit_id', name='uq_review_state_user_unit')
    )
    op.create_index('idx_review_state_due', 'review_state', ['user_id', 'next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_state_due', table_name='review_state')
    op.drop_table('review_state')
    op.drop_index('idx_review_history_unit_offset', table_name='review_history')
    op.drop_table('review_history')
    op.drop_table('learning_artifact_units')
    op.drop_index('idx_ku_relations_unit', table_name='knowledge_unit_relations')
    op.drop_table('knowledge_unit_relations')
    op.drop_index('idx_profile_entries_user', table_name='knowledge_profile_entries')
    op.drop_table('knowledge_profile_entries')
    op.drop_table('independence_metrics')
    op.drop_table('format_decisions')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_knowledge_units_user_time', table_name='knowledge_units')
    op.drop_index('idx_knowledge_units_project', table_name='knowledge_units')
    op.drop_table('knowledge_units')
    op.drop_index('idx_sessions_user_project', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_projects_user', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_metrics_events_user', table_name='metrics_events')
    op.drop_table('metrics_events')
    op.drop_index('idx_artifacts_user', table_name='learning_artifacts')
    op.drop_table('learning_artifacts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
